# Generated by Django 3.1.2 on 2020-10-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daytasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='status',
            field=models.CharField(default='Completed', max_length=20),
            preserve_default=False,
        ),
    ]
