# Generated by Django 3.1.2 on 2020-10-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daytasks', '0002_todolist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('To Do', 'To Do')], default='Completed', max_length=20),
        ),
    ]
